#!/usr/bin/perl

=head1 NAME

zmdailyreport - report on email usage

=head1 SYNOPSIS

Usage: zmdailyreport [options]

  Options:
    --mail                 Send report via email, default is stdout
    --help                 This help message
    --product		   Is ChmailProduct or not	

=cut
#    --user <email_address> Report usage for <email_address> only
#    --time <start>,<end>   Default is midnight to midnight of the previous day
#    --now                  Shortcut for midnight to the current time
use warnings;
use strict;
use Pod::Usage qw(pod2usage);
use lib "/opt/Chmail/Chmailmon/lib";
use Chmail::Util::Common;
use Chmail::Mon::Logger;
use Getopt::Long qw(GetOptions);
use Mail::Mailer ();
use POSIX qw(strftime setlocale LC_TIME);
use Time::Local qw(timelocal);
my ( %Opt, $Debug );

GetOptions( \%Opt, "mailreport", "now", "debug", "user=s", "time=s", "help", "product" )
  or pod2usage( -exitval => 2 );
  
pod2usage( -exitval => 1, -verbose => 0 ) if ( $Opt{help} );

$Debug = $Opt{debug};

setlocale(LC_TIME, "C");
my $stdout;
open($stdout, ">&STDOUT") || die $!;
pipe(PFIN, PFOUT);
pipe(MIN, MOUT);
my $fhin = fileno(PFIN);
close(STDIN);
open(STDIN, "<&=$fhin") || die $!;


if (fork()) {
	close(MOUT);
	my $today = strftime("%b %e ", localtime);
	my $datestring = strftime("%F", localtime);
	my $ymd = strftime("%Y%m%d", localtime);
	
	my $found = 0;
	my $old_log;
	if (-f "/var/log/Chmail.log.1.gz") {
		$old_log = "gzip -dc /var/log/Chmail.log.1.gz |";
	} elsif (-f "/var/log/Chmail.log-$ymd.gz") {
		$old_log = "bzip2 -dc /var/log/Chmail.log-$ymd.gz |";
	} elsif (-f "/var/log/Chmail.log.1.bz2") {
		$old_log = "bzip2 -dc /var/log/Chmail.log.1.bz2 |";
	} elsif (-f "/var/log/Chmail.log-$ymd.bz2") {
		$old_log = "bzip2 -dc /var/log/Chmail.log-$ymd.bz2 |";
	}
	if (defined($old_log)) {
	    if (open(LOG, $old_log)) {
	    	
            while (<LOG>) {
		        my $line = $_;
		        if ($line =~ /$today/o) {
   		             print PFOUT $line;
   		             $found = 1;
	            } elsif ($found) {
	    	        last; # don't scan any further, we've exhausted today's logs
	            }
	        }
		    close(LOG);
	    }
		
	}
	system("/opt/Chmail/libexec/prepflog.pl -d today  /var/log/Chmail.log > /opt/Chmail/log/postfix.log");
	system("chown Chmail.Chmail /opt/Chmail/log/postfix.log");
	open(LOG, "</opt/Chmail/log/postfix.log") || die $!;
	$found = 0;
	while (<LOG>) {
		my $line = $_;
		if ($line =~ /$today/o) {
   		     print PFOUT $line;
   		     $found = 1;
	    } elsif ($found) {
	    	last; # don't scan any further, we've exhausted today's logs
	    }
	}
	close(LOG);
	close(PFOUT);
	
	my @Report;
	while (<MIN>) {
		push(@Report, $_);
	}
	close (MIN);
	
	if ($Opt{mailreport}) {
		sendEmailReport(day => $datestring, data => \@Report);
	} else {
		print @Report;
	}
} else {
	close(PFOUT);
	close(MIN);
	open(STDOUT, ">&MOUT") || die $!;
	my $user_limit = getLocalConfig('Chmail_mtareport_max_users') || 50;
	my $host_limit = getLocalConfig('Chmail_mtareport_max_hosts') || 50;
	$user_limit = 50 if $user_limit !~ /^\d+/;
	$host_limit = 50 if $host_limit !~ /^\d+/;
	@ARGV = ('-u', $user_limit, '-h', $host_limit);
    do '/opt/Chmail/libexec/pflogsumm.pl';
if ($Opt{product}) {
    print "\n\nToday logins:\n";
    print "---------------\n";
    my $user=`id -u`;
if ($user == '0')
{
system("su - Chmail -c 'zmaccts' | grep  `date +%m/%d/%y` | tr -s ' ' | cut -d ' ' -f1,5,6");
print "Total logins: ";
system("su - Chmail -c 'zmaccts' | grep  `date +%m/%d/%y` | grep @ | wc -l");
}
else
{
system("/opt/Chmail/bin/zmaccts | grep  `date +%m/%d/%y` | tr -s ' ' | cut -d ' ' -f1,5,6");
print "Total logins: ";
system("/opt/Chmail/bin/zmaccts | grep  `date +%m/%d/%y` | grep @ | wc -l");
}
close(STDOUT);
}
else
{
    close(STDOUT);
}
}
{    # avoid making $LocalConfig global
    my $LocalConfig;

    sub getLocalConfig {
        my $key = shift;
        $LocalConfig = loadLocalConfig() unless ($LocalConfig);
        return $LocalConfig->{$key};
    }
}

sub loadLocalConfig {
    my %conf;

    open( CONF, "/opt/Chmail/bin/zmlocalconfig -s -q -m shell |" )
      or die("Open local config failed: $!\n");

    while (<CONF>) {
        chomp;
        my ( $key, $val ) = split( /=/, $_, 2 );
        $val =~ s/';$//;
        $val =~ s/^'//;
        $conf{$key} = $val;
    }
    die("No data returned from local config") unless ( keys %conf );
    return \%conf;
}

sub getLdapConfigValue {
    my $attrib = shift;

    return (undef) unless ($attrib);

    my $val = getLdapServerConfigValue($attrib);
    print "Server: $val\n" if $Debug;
    $val = getLdapGlobalConfigValue($attrib) if ($val eq "");
    print "Global: $val\n" if $Debug;
    return $val;
}

sub getLdapServerConfigValue {
    my $attrib = shift;

    return (undef) unless ($attrib);
    my $server = getLocalConfig("Chmail_server_hostname");
    # could consider redirecting STDERR to /dev/null
    open( CONF, "/opt/Chmail/bin/zmprov -l gs $server '$attrib' |" )
      or die("Open global config failed: $!");

    my ( $key, $val );
    while (<CONF>) {
        chomp;
        next if (/^#/);
        ( $key, $val ) = split( /:\s*/, $_, 2 );
        # for now just assume a single value/attribute is requested
        last if ($val);
    }
    return $val;
}

sub getLdapGlobalConfigValue {
    my $attrib = shift;

    return (undef) unless ($attrib);

    # could consider redirecting STDERR to /dev/null
    open( CONF, "/opt/Chmail/bin/zmprov -l gcf '$attrib' |" )
      or die("Open global config failed: $!");

    my ( $key, $val );
    while (<CONF>) {
        chomp;
        ( $key, $val ) = split( /:\s*/, $_, 2 );

        # for now just assume a single value/attribute is requested
        last if ($val);
    }
    return $val;
}

sub sendEmailReport {
    my %arg = @_;

    my $data = $arg{data};    # @Report data for message body

    my $subject      = "Daily mail report for $arg{day}";
    my $from_address = getLocalConfig("smtp_source");
    my $to_address   = getLocalConfig("smtp_destination");
    my $smtphost     = getLdapConfigValue("ChmailSmtpHostname") || "localhost";

    warn("DEBUG: Sending daily report to $to_address via $smtphost\n")
      if ($Debug);

    eval {
        my $mailer = Mail::Mailer->new( "smtp", Server => $smtphost );
        $mailer->open(
            {
                From    => $from_address,
                To      => $to_address,
                Subject => $subject,
            }
        );
        print $mailer @$data;
        $mailer->close();
    };
    if ($@) {
        logError("Failed to email report using SMTP via '$smtphost': $@\n");
    }
    else {
        warn("DEBUG: Email report sent to $to_address\n") if ($Debug);
    }
}
